### ISSUE TITLE
liquidhaskell Cabal flag is not used anywhere

### ISSUE THREAD

**Issue by peti** [spinda/liquidhaskell-cabal-demo#3]
The Cabal file defines a flag `liquidhaskell` that defaults to `False`. Anyhow, the flag is never referenced anywhere. My guess is that it can be dropped entirely.

**Comment by spinda** [comment]
The `liquidhaskell` flag is picked up by `liquidhaskell-cabal` and used to enable Liquid Haskell verification during the build. See the [`liquidhaskell-cabal` README](https://github.com/spinda/liquidhaskell-cabal#usage).
